name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          # No longer in use: docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }} .
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .
          
      - name: Push Docker image to ECR
        run: |
          # No longer in use: docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest
