on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start instance refresh 
        run: |
            aws autoscaling start-instance-refresh \
            --auto-scaling-group-name spotify-setlist-autoscaling-group \
            --preferences '{"SkipMatching": false }'
